### PR TITLE
Updates ansible-core & collection versions for Base and Minimal

### PR DESCRIPTION
**Pull request by anweshadas**

### CODE REVIEW

**Comment by felixfontein** [comment]
ansible.utils (5.1.2) and ansible.posix (1.6.1) have newer verisons BTW.

**Comment by samccann** [comment]
@felixfontein -were these newer versions available when the PR was created? Just wondering if we need to update process docs somewhere to remind us to pull in the appropriate versions. Since both EEs are tied to a core version, I guess it's just pull in the most recent collection version, right?

**Comment by felixfontein** [comment]
@samccann yes there were. ansible.posix 5.0.0 even got released four months ago.

I'm wondering whether the versions are related to the collection versions included in Ansible 10. That would explain the version numbers that they use right now.

**Comment by samccann** [comment]
Good question. I originally thought they were the collections in Ansible 10, but now I don't really know. The EE includes ansible-core, so it 'could' work with the most recent collection....

**Comment by felixfontein** [comment]
If they are supposed to be the same versions that are included in Ansible 10, then everything's ok.

**Pull request merged**
