### PR TITLE
CentOS Stream 8: try to get en_US.UTF-8

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Review by russoz — COMMENTED** [review]
Not familiar with buildah but it seems pretty straightforward. LGTM.

**Comment by felixfontein** [comment]
@russoz thanks for reviewing this!

**Comment by dmsimard** [comment]
@felixfontein no objection (sorry for the delay), though could you describe what this solves ?

Were there errors about locales ?

I noted that there's a similar command in the ansible-test container definitions as well: https://github.com/ansible/distro-test-containers/blob/f37e625d1d2529d78b6ee511900ae1f27c5a6ed5/fedora35-test-container/Dockerfile#L61

**Comment by felixfontein** [comment]
@dmsimard the CentOS Stream 8 tests have been failing also for some time now, like here: https://github.com/ansible-community/images/runs/5995952704?check_suite_focus=true The problem is that some code in ansible-core assumes that en_US.UTF-8 is present; I think this comes from ansible-test setting `LC_ALL='en_US.UTF-8'` (and ansible-core then assuming indirectly that the locale mentioned in `LC_ALL` exists?).

**Pull request merged**
