### PR TITLE
Run GHA tests with Podman and Docker

### PR DESCRIPTION
**Pull request by felixfontein**
Ref: https://github.com/ansible-community/images/issues/9#issuecomment-1193351413

### CODE REVIEW

**Comment by dmsimard** [comment]
> Build failed.
> 
> x [community-images-ansible-test-build ](https://ansible.softwarefactory-project.io/zuul/build/0271aef6cea94e73b002d0dcf905b685) **FAILURE** in 7m 35s

FWIW, unrelated:
```
downloading required keys...
:: Import PGP key 139B09DA5BF0D338, "David Runge <dvzrv@archlinux.org>"? [Y/n] 
checking package integrity...
error: libcap: key "991F6E3F0765CF6295888586139B09DA5BF0D338" is unknown
:: Import PGP key 991F6E3F0765CF6295888586139B09DA5BF0D338? [Y/n] 
:: File /var/cache/pacman/pkg/libcap-2.65-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)

Errors occurred, no packages were upgraded.
```

**Comment by dmsimard** [comment]
It works for archlinux and debian bullseye but it fails for centos-stream8 here: https://github.com/ansible-community/images/runs/7520257659?check_suite_focus=true#step:9:163
Screenshot from 2022-07-27 22-59-11

From a previous centos-stream8 run with ``docker exec`` instead of ``podman exec``: https://github.com/ansible-community/images/runs/7520006303?check_suite_focus=true#step:9:139
Screenshot from 2022-07-27 23-03-25

I'm not really sure what's the issue but I did find this recurring warning in the logs (github issue here: https://github.com/containers/podman/issues/11745):
Screenshot from 2022-07-27 23-11-52

The podman that gets installed in the "install dependencies" step of the GHA is ``already the newest version (100:3.4.2-5)``.
3.4.2 dates back to [November 2021](https://github.com/containers/podman/releases/tag/v3.4.2) while 4.1.1 was release last June and a 4.2.0 is coming soon.

I'm curious if it would work with a more recent version ?

**Comment by dmsimard** [comment]
> The podman that gets installed in the "install dependencies" step of the GHA is already the newest version (100:3.4.2-5).
3.4.2 dates back to [November 2021](https://github.com/containers/podman/releases/tag/v3.4.2) while 4.1.1 was release last June and a 4.2.0 is coming soon.

> I'm curious if it would work with a more recent version ?

The GHA runs ubuntu-latest which is really 20.04 as per: https://github.com/actions/virtual-environments#available-environments

Could we try that "beta" ubuntu-22.04 image ? It apparently has podman 3.4.4 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#tools

It's not 4.1.1 but there's a good amount of bug fixes in 3.4.3 and 3.4.4.

**Comment by felixfontein** [comment]
> > Build failed.
> > x [community-images-ansible-test-build ](https://ansible.softwarefactory-project.io/zuul/build/0271aef6cea94e73b002d0dcf905b685) **FAILURE** in 7m 35s
> 
> FWIW, unrelated:
> 
> ```
> downloading required keys...
> :: Import PGP key 139B09DA5BF0D338, "David Runge <dvzrv@archlinux.org>"? [Y/n] 
> checking package integrity...
> error: libcap: key "991F6E3F0765CF6295888586139B09DA5BF0D338" is unknown
> :: Import PGP key 991F6E3F0765CF6295888586139B09DA5BF0D338? [Y/n] 
> :: File /var/cache/pacman/pkg/libcap-2.65-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)
> 
> Errors occurred, no packages were upgraded.
> ```

I fixed that in https://github.com/ansible-community/images/pull/25.

**Comment by felixfontein** [comment]
> Could we try that "beta" ubuntu-22.04 image ? It apparently has podman 3.4.4 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#tools

I pushed a commit, let's see...

**Comment by dmsimard** [comment]
> > Could we try that "beta" ubuntu-22.04 image ? It apparently has podman 3.4.4 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#tools
> 
> I pushed a commit, let's see...

Still the same error, I guess it's something else.

**Comment by gotmax23** [comment]
Is it possible to run ansible-test with more verbosity here to try and see what's wrong? I *believe* that shows more about which podman commands are actually used. I suppose I can try later to locally reproduce this.

**Comment by gotmax23** [comment]
It looks like the other containers that were previously failing on podman are working now, right?

**Comment by felixfontein** [comment]
> It looks like the other containers that were previously failing on podman are working now, right?

They do, but they already did before adding your suggested fix (`loginctl enable-linger runner` followed by `sleep 1`).



> Is it possible to run ansible-test with more verbosity here to try and see what's wrong? I _believe_ that shows more about which podman commands are actually used. I suppose I can try later to locally reproduce this.

Extra verbosity doesn't help. The commands that are used are already printed with `-v` (which is already there). The problem is that the `ssh` daemon isn't starting (and thus neither ansible-test nor ansible-core can connect to the container with SSH - ansible-test is first trying it multiple times, that are the `ssh` commands in the verbose output, and eventually gives up and starts ansible-core anyway, which also cannot connect). As to why it isn't starting, that's probably systemd again. I have (or had, haven't tried it for some time) that when I try to use ansible-test with docker instead of podman on my machine. I don't remember the details (or whether I ever properly found out about them), but for some reason systemd isn't starting up properly (it might just hang instead of starting or exiting, and thus not starting the ssh daemon)... It is clear that it is not simply exiting since otherwise ansible-test would complain about the container being gone. (I think that was the error we saw earlier this year.)

**Comment by felixfontein** [comment]
It finally works! :tada:

**Comment by felixfontein** [comment]
This is now ready for review.

**Comment by felixfontein** [comment]
@dmsimard @gotmax23 any comments on this? If not I'll just merge.

**Review by gotmax23 — APPROVED** [review]

**Comment by felixfontein** [comment]
@dmsimard @gotmax23 thanks a lot for your comments and reviews!

**Pull request merged**
