### PR TITLE
Make EE a proper EE with dependencies installed

### PR DESCRIPTION
**Pull request by felixfontein**
By just running `pip install ansible`, all EE requirements specified by the collections are ignored. By installing the Ansible 5 collections from galaxy (using https://raw.githubusercontent.com/ansible-community/ansible-build-data/main/5/galaxy-requirements.yaml), all dependencies will be included in the EE.

### CODE REVIEW

**Comment by felixfontein** [comment]
Unsurprisingly, we have a dependency problem, where community.okd's dependency screws this up. They **really** need to fix their collection.

**Comment by felixfontein** [comment]
I created an issue for this in community.okd (https://github.com/openshift/community.okd/issues/148).

**Comment by felixfontein** [comment]
Restarting tests

**Comment by gundalow** [comment]
Do/should we include the Python etc dependencies that the Collections may have?
https://github.com/ansible-collections/junipernetworks.junos/blob/main/bindep.txt

**Comment by felixfontein** [comment]
@gundalow that's what this PR is doing, and that's what now makes it fail:
```
- 'azure-mgmt-resource==10.2.0,>=16.1.0  # from collection azure.azcollection,netapp.cloudmanager'
```
That's something that can't be satisfied...

**Comment by felixfontein** [comment]
I've upgraded the PR to change the EE to "ansible-core 2.14 with Ansible 7". This won't work for two reasons:
1. quay.io/ansible/ansible-runner:stable-2.14-latest does not exist.
2. I'm not 100% sure about that, but I guess it will fail for the same reason as before (contradicting versions).

**Comment by it-pappa** [comment]
Wow, i started on this role and im glad i found this thread. So there is no way of trying to build an EE for community.general?

**Comment by felixfontein** [comment]
@it-pappa this is about creating an EE for all of the community Ansible package, not about community.general - in fact community.general is kind of ignored here since it does not declare EE dependencies. There's a separate discussion on that: https://github.com/ansible-collections/community.general/issues/4512

The TLDR is: c.g has such a huge set of dependencies, only some of them needed inside the EE and quite a few needed on the remote, that just declaring everything for EEs neither makes sense, nor does there exist good tooling for doing this in a useful way.

**Comment by it-pappa** [comment]
> @it-pappa this is about creating an EE for all of the community Ansible package, not about community.general - in fact community.general is kind of ignored here since it does not declare EE dependencies. There's a separate discussion on that: [ansible-collections/community.general#4512](https://github.com/ansible-collections/community.general/issues/4512)
> 
> The TLDR is: c.g has such a huge set of dependencies, only some of them needed inside the EE and quite a few needed on the remote, that just declaring everything for EEs neither makes sense, nor does there exist good tooling for doing this in a useful way.

yes correct. I have been on for a whole day of creating roles to clone vms etc for proxmox. I think it will be easier for me just to fetch the proxmox modules from the collection myself, and create a new EE for use with proxmox and it dependencies since for what i understand it only needs two required pythin packages.

**Comment by felixfontein** [comment]
I'm closing this since this project looks impossible to realize...

**Pull request closed without merging**
